steps:
  # Build the Go application
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'function', './cmd/cloudfunction']
    env:
      - 'GO111MODULE=on'

  # Deploy the function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'functions'
      - 'deploy'
      - 'multilingual-video-processor'
      - '--gen2'
      - '--runtime=go123'
      - '--region=us-central1'
      - '--source=.'
      - '--entry-point=TranslateVideo'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--memory=4096MB'
      - '--timeout=540s'
      - '--set-env-vars'
      - 'GCS_BUCKET_OUTPUT=${_GCS_BUCKET_OUTPUT},GOOGLE_TRANSLATE_API_KEY=${_GOOGLE_TRANSLATE_API_KEY}'

options:
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _GCS_BUCKET_OUTPUT: 'your-output-bucket'
  _GOOGLE_TRANSLATE_API_KEY: ''

timeout: '1200s'